require("otso.plugins-setup")
require("otso.core.colorscheme")
require("otso.core.keymaps")
require("otso.core.options")

-- Plugins --
require("otso.plugins.nvim-tree")
require("otso.plugins.comment")
require("otso.plugins.lualine")
require("otso.plugins.telescope")
require("otso.plugins.nvim-cmp")
require("otso.plugins.lsp.mason")
require("otso.plugins.lsp.lspconfig")
require("otso.plugins.lsp.lspsaga")
require("otso.plugins.lsp.null-ls")
require("otso.plugins.autopairs")
require("otso.plugins.treesitter")
require("otso.plugins.gitsigns")
require("otso.plugins.dashboard")
require("otso.plugins.barbar")
require("otso.plugins.harpon")
require("otso.plugins.undotree")
require("otso.plugins.nvim-orgmode")
require("otso.plugins.alpha")
require("otso.plugins.obsidian")
require("leap").add_default_mappings()
